### ISSUE TITLE
No batch-training?

### ISSUE THREAD

**Issue by DreamerDeo** [ryanzhumich/editsql#10]
https://github.com/ryanzhumich/editsql/blob/a381be845c10a8fb614cebdb2d81fed77756489e/model_util.py#L186
What the meaning of batch-size in sparc/spider setting?

**Comment by ryanzhumich** [comment]
Hi, Longxu,

Thanks! Our implementation uses only 1 interaction in the interaction_batch. This is because (1) it is hard to implement batch_size>1 for interactions, and (2) memory could be an issue when batch_size>1.

The batch_size is used to normalize the loss of each example by dividing the batch_size (https://github.com/ryanzhumich/editsql/blob/master/model/schema_interaction_model.py#L466)

Implementing batch_size>1 for Spider (which is not interaction) is possible, but not available yet...

Best,
Rui

**Comment by DreamerDeo** [comment]
Hi, Rui

Thanks for your prompt reply! 
And is there an independent model for Spider? Currently, all those three datasets are trained with the model `scheme_interaction_model`. The function `train_epoch_with_utterances` trains model for a single epoch given batches of utterance data, but no model has been called in `run.py`.

Best,
Longxu

**Comment by ryanzhumich** [comment]
You are welcome. You are correct, train_epoch_with_utterances could be used for Spider. But sorry we currently do not have such an implementation.

**Comment by DreamerDeo** [comment]
Thanks for your job!
