### ISSUE TITLE
Does editsql also give a prediction on value in SQL conditions ? 

### ISSUE THREAD

**Issue by WaNePr** [ryanzhumich/editsql#15]
If editsql gives a prediction on value in SQL conditions, please point out where it is in the code.
If not, how should we do it ?

**Comment by ryanzhumich** [comment]
Hi,

Thanks for this question. EditSQL does not predict values in SQL.

In order to generate values, the model should be able to 
1) copy from the question inputs
2) retrieve from the database content (database content is available)
3) generate numbers (e.g. 1 or 3 after LIMIT in some SQL queries)

more information is available at https://yale-lily.github.io/spider

Hope this helps.

Best,
Rui
